version: "3.9"

services:
  wordpress:
    build: .
    container_name: petertimbs-wordpress
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: petertimbs_db
      PHP_MEMORY_LIMIT: 2048M
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: petertimbs-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petertimbs_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: petertimbs-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root


volumes:
  db_data:
